### ISSUE TITLE
Dash shouldn't periodically auto open metamask

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/admin-ui#4]
If I leave a tab open with the dash, every couple hours it will auto open metamask. It doesn't appear to be asking for a connect or signature, it just wants it open. Maybe this happens when metamask locks? In any case, it's kind of alarming. 

In all cases, we should require some user action for metamask to open.

**Comment by awmuncy** [comment]
Fixed here: https://github.com/tablelandnetwork/admin-ui/commit/b943b7e8d25e7e8681c5bb002badea23a6886150

**Comment by sanderpick** [comment]
🙏
